name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - test
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run tests with coverage
        working-directory: ./backend
        run: npm test -- --coverage --coverageReporters=lcov
        env:
          NODE_ENV: test

      - name: Verify coverage file exists
        run: |
          if [ -f "backend/coverage/lcov.info" ]; then
            echo "✅ Coverage file found"
            ls -lh backend/coverage/lcov.info
          else
            echo "❌ Coverage file not found"
            exit 1
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      # Generate this token in SonarCloud
        with:
          args: >
            -Dsonar.verbose=true
